INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('1', '제목1', '내용1');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('2', '제목2', '내용2');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('3', '제목3', '내용3');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('4', '제목4', '내용4');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('5', '제목5', '내용5');
INSERT INTO BOARD(ID, TITLE, CONTENT) VALUES ('6', '제목6', '내용6');